export type VendorTag = "Top Rated" | "Popular" | "Featured" | "New";

export interface PricingTier {
  name: "Basic" | "Standard" | "Premium";
  price: string;
  inclusions: string[];
}

export interface Vendor {
  id: string;
  name: string;
  category: string;
  location: string;
  priceRange: string;
  rating: number;
  reviews: number;
  tag: VendorTag;
  description: string;
  bio: string[];
  yearsExperience: number;
  weddingsDone: number;
  responseTime: string;
  services: string[];
  pricingTiers: PricingTier[];
}

export const vendors: Vendor[] = [
  {
    id: "golden-hour-studio",
    name: "Golden Hour Studio",
    category: "Photography",
    location: "Austin, TX",
    priceRange: "$$–$$$",
    rating: 4.9,
    reviews: 127,
    tag: "Top Rated",
    description:
      "Cinematic storytelling for your wedding day. Golden Hour Studio captures the raw emotion and quiet magic of each moment with a warm, editorial eye.",
    bio: [
      "Golden Hour Studio was founded by award-winning photographer Maya Chen, whose approach to wedding photography blends photojournalism with fine-art editorial. Maya believes every wedding has a unique story waiting to be told — and she's dedicated to capturing it authentically.",
      "With over a decade of experience shooting weddings across Texas and beyond, Maya and her team have developed a signature style: sun-drenched tones, candid emotion, and beautifully composed portraits that feel both timeless and utterly personal.",
      "From intimate backyard ceremonies to grand ballroom celebrations, Golden Hour Studio brings the same level of care and artistry to every event. Couples consistently describe working with Maya as effortless — she blends into the day naturally, so you'll barely know the camera is there.",
    ],
    yearsExperience: 11,
    weddingsDone: 340,
    responseTime: "Within 12 hours",
    services: [
      "Full-day wedding coverage",
      "Engagement sessions",
      "Bridal portraits",
      "Second shooter available",
      "High-resolution digital gallery",
      "Print products available",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$2,200",
        inclusions: [
          "6 hours of coverage",
          "1 photographer",
          "400+ edited digital images",
          "Online gallery (12 months)",
          "Print release",
        ],
      },
      {
        name: "Standard",
        price: "$3,600",
        inclusions: [
          "8 hours of coverage",
          "1 photographer + 1 assistant",
          "700+ edited digital images",
          "Online gallery (unlimited)",
          "Engagement session included",
          "Print release",
        ],
      },
      {
        name: "Premium",
        price: "$5,500",
        inclusions: [
          "10 hours of coverage",
          "2 photographers",
          "1,000+ edited digital images",
          "Online gallery (unlimited)",
          "Engagement session included",
          "10×10 flush mount album",
          "Rush delivery option",
        ],
      },
    ],
  },
  {
    id: "bloom-and-co",
    name: "Bloom & Co.",
    category: "Florals & Decor",
    location: "Dallas, TX",
    priceRange: "$$",
    rating: 4.8,
    reviews: 89,
    tag: "Popular",
    description:
      "Lush, romantic floral design rooted in seasonal blooms. Bloom & Co. transforms venues into breathtaking garden escapes your guests will never forget.",
    bio: [
      "Bloom & Co. is a Dallas-based floral design studio led by founder and head designer Isabelle Torres. Known for her lush, garden-to-table aesthetic, Isabelle draws inspiration from the natural world to create arrangements that feel organic, abundant, and deeply romantic.",
      "The studio specialises in full-service floral design — from ceremony arches and reception centrepieces to bespoke bridal bouquets and bud vase tablescapes. Isabelle works closely with each couple to understand their vision, palette, and venue before crafting a cohesive floral story.",
      "Bloom & Co. sources blooms seasonally from local Texas farms and international growers, ensuring the freshest quality and sustainability at every event. Whether you're dreaming of wildflower meadow vibes or classic white peonies, Isabelle and her team bring it to life.",
    ],
    yearsExperience: 8,
    weddingsDone: 220,
    responseTime: "Within 24 hours",
    services: [
      "Bridal & bridesmaid bouquets",
      "Ceremony arch and altar florals",
      "Reception centrepieces",
      "Bud vase and blossom bar",
      "Flower wall installations",
      "Rehearsal dinner florals",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$1,800",
        inclusions: [
          "Bridal bouquet",
          "2 bridesmaid bouquets",
          "Ceremony arch arrangement",
          "6 centrepieces",
          "Setup & delivery",
        ],
      },
      {
        name: "Standard",
        price: "$3,200",
        inclusions: [
          "Bridal bouquet",
          "4 bridesmaid bouquets",
          "Ceremony arch + aisle",
          "12 centrepieces",
          "Head table garland",
          "Setup & breakdown",
        ],
      },
      {
        name: "Premium",
        price: "$5,800",
        inclusions: [
          "Bridal + bridesmaid bouquets (full party)",
          "Ceremony arch + full aisle",
          "20 centrepieces",
          "Flower wall installation",
          "Cocktail florals",
          "Full setup & breakdown",
          "Dedicated floral coordinator",
        ],
      },
    ],
  },
  {
    id: "rhythm-collective",
    name: "The Rhythm Collective",
    category: "Music & DJ",
    location: "Houston, TX",
    priceRange: "$$",
    rating: 4.7,
    reviews: 64,
    tag: "Popular",
    description:
      "From cocktail hour jazz to late-night dance floors, The Rhythm Collective curates the perfect soundtrack for every moment of your celebration.",
    bio: [
      "The Rhythm Collective is Houston's most-booked wedding music and DJ service, led by founder Marcus Webb. With roots in live performance and a deep love for event atmosphere, Marcus blends professional DJ sets with live instrumentation to create unforgettable soundscapes.",
      "What sets The Rhythm Collective apart is their ability to read a room. Whether your guests are sipping champagne during cocktail hour or throwing shapes at midnight, Marcus and his team know exactly what to play and when. They work with couples to build custom playlists that reflect their taste and story.",
      "The team is also known for their flawless MC work — keeping the schedule on track without being cheesy, and making every announcement feel natural and warm. From first dance to last song, The Rhythm Collective keeps the energy alive.",
    ],
    yearsExperience: 9,
    weddingsDone: 180,
    responseTime: "Within 24 hours",
    services: [
      "Full reception DJ service",
      "Live saxophonist add-on",
      "Ceremony music (Bluetooth/speaker)",
      "Cocktail hour playlist",
      "MC & announcements",
      "Photo booth music pairing",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$1,400",
        inclusions: [
          "4 hours of DJ service",
          "Reception only",
          "Curated playlist consultation",
          "Professional sound system",
          "MC announcements",
        ],
      },
      {
        name: "Standard",
        price: "$2,400",
        inclusions: [
          "6 hours of DJ service",
          "Ceremony + cocktail + reception",
          "Custom playlist build",
          "Professional sound system",
          "Wireless microphone",
          "MC announcements",
        ],
      },
      {
        name: "Premium",
        price: "$3,800",
        inclusions: [
          "8 hours of DJ service",
          "Full day coverage",
          "Live saxophonist (2 hours)",
          "Premium sound & lighting",
          "Custom monogram projector",
          "MC announcements",
          "Photo booth setup",
        ],
      },
    ],
  },
  {
    id: "harvest-table",
    name: "Harvest Table Co.",
    category: "Catering",
    location: "San Antonio, TX",
    priceRange: "$$$",
    rating: 4.8,
    reviews: 112,
    tag: "Featured",
    description:
      "Farm-to-table wedding catering that celebrates Texas produce and local flavours. Harvest Table crafts menus that are as memorable as the day itself.",
    bio: [
      "Harvest Table Co. is a boutique catering company born from a deep respect for seasonal, locally sourced ingredients. Founded by executive chef Daniel Reyes, the company has spent over a decade delivering elevated dining experiences for weddings, corporate events, and private celebrations across San Antonio and beyond.",
      "Chef Daniel works directly with Texas farms, ranchers, and artisan producers to build menus that change with the seasons. Every menu is a collaboration — couples sit down with the team for a full tasting and customisation session, ensuring the food reflects their heritage, preferences, and vision.",
      "From plated multi-course dinners to rustic family-style spreads and late-night taco bars, Harvest Table handles everything from staffing to service ware. They're known for making guests feel like they've eaten at a private restaurant rather than a wedding.",
    ],
    yearsExperience: 14,
    weddingsDone: 290,
    responseTime: "Within 48 hours",
    services: [
      "Plated dinner service",
      "Family-style reception dining",
      "Cocktail hour canapés",
      "Wedding cake cutting service",
      "Late-night snack stations",
      "Full bar setup & service",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$65/head",
        inclusions: [
          "2-course plated meal",
          "Non-alcoholic beverages",
          "Professional serving staff",
          "Setup & clean-up",
          "Standard service ware",
        ],
      },
      {
        name: "Standard",
        price: "$95/head",
        inclusions: [
          "3-course plated meal",
          "Cocktail hour canapés (6 varieties)",
          "Full non-alcoholic bar",
          "Professional serving staff",
          "Premium service ware",
          "Wedding cake cutting included",
        ],
      },
      {
        name: "Premium",
        price: "$145/head",
        inclusions: [
          "5-course tasting menu",
          "Cocktail hour canapés (12 varieties)",
          "Open bar (5 hours)",
          "Late-night snack station",
          "Dedicated event captain",
          "Custom menu design",
          "Complete linen & tableware",
        ],
      },
    ],
  },
  {
    id: "eternal-bands",
    name: "Eternal Bands",
    category: "Jewellery",
    location: "Austin, TX",
    priceRange: "$$$–$$$$",
    rating: 5.0,
    reviews: 41,
    tag: "Featured",
    description:
      "Bespoke wedding bands and engagement rings crafted by hand in Austin. Eternal Bands works one-on-one with couples to design pieces as unique as their love.",
    bio: [
      "Eternal Bands was founded by master jeweller Lena Park, who left a career in corporate design to pursue her true passion: creating heirloom jewellery that tells a love story. Every ring made at Eternal Bands is crafted by hand in Lena's Austin studio, using ethically sourced metals and conflict-free stones.",
      "The design process is deeply personal. Each couple begins with a consultation where Lena walks through styles, settings, and custom options. Whether you're after a classic solitaire, a vintage-inspired halo, or something completely original, Lena translates your vision into a wearable work of art.",
      "Eternal Bands is known for attention to detail that borders on obsessive — from the way light catches a bezel setting to the engraving of initials inside each band. Couples often say receiving their rings is the moment the wedding truly feels real.",
    ],
    yearsExperience: 7,
    weddingsDone: 95,
    responseTime: "Within 12 hours",
    services: [
      "Custom engagement ring design",
      "Wedding band sets (his & hers)",
      "Ring resizing & restoration",
      "Stone sourcing & certification",
      "Engraving services",
      "Anniversary upgrades",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "From $1,200",
        inclusions: [
          "Wedding band (single)",
          "Sterling silver or gold-fill",
          "Standard engraving",
          "Velvet gift box",
          "1-year polish warranty",
        ],
      },
      {
        name: "Standard",
        price: "From $3,500",
        inclusions: [
          "Matching band set (pair)",
          "14K gold (yellow/white/rose)",
          "Semi-precious stone setting",
          "Custom engraving",
          "Certificate of authenticity",
          "Lifetime resizing",
        ],
      },
      {
        name: "Premium",
        price: "From $7,500",
        inclusions: [
          "Bespoke engagement ring + band set",
          "18K gold or platinum",
          "Lab-grown or natural diamond",
          "Full design consultation",
          "GIA certification",
          "Heirloom gift box",
          "Lifetime warranty & care",
        ],
      },
    ],
  },
  {
    id: "glow-grace",
    name: "Glow & Grace Studio",
    category: "Beauty & Hair",
    location: "Dallas, TX",
    priceRange: "$$",
    rating: 4.9,
    reviews: 156,
    tag: "Top Rated",
    description:
      "Bridal beauty that lasts all day and photographs beautifully. Glow & Grace Studio is Dallas's most sought-after team for wedding hair and makeup.",
    bio: [
      "Glow & Grace Studio is a bridal beauty collective led by founder and lead artist Sofia Alvarez. The team specialises exclusively in wedding-day hair and makeup, with every service designed for longevity, photography, and — most importantly — making you feel like yourself at your most stunning.",
      "Sofia built Glow & Grace after years of seeing brides disappointed by heavy, cakey looks that didn't translate to photos. Her philosophy is 'enhanced natural' — amplifying each client's best features with a light hand and premium products that stay fresh from ceremony to last dance.",
      "The studio offers on-location service across the Dallas–Fort Worth area, with a full team available for large bridal parties. Every booking includes a trial session so there are zero surprises on the big day.",
    ],
    yearsExperience: 10,
    weddingsDone: 410,
    responseTime: "Within 6 hours",
    services: [
      "Bridal hair styling",
      "Bridal makeup application",
      "Bridesmaid hair & makeup",
      "Bridal trial sessions",
      "Airbrush foundation",
      "On-location service",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$380",
        inclusions: [
          "Bridal hair styling",
          "Bridal makeup",
          "On-location (DFW area)",
          "Touch-up kit",
          "1 hour of service",
        ],
      },
      {
        name: "Standard",
        price: "$680",
        inclusions: [
          "Bridal hair + makeup",
          "1 bridesmaid hair or makeup",
          "Trial session (1 look)",
          "Airbrush foundation available",
          "On-location (DFW area)",
          "Touch-up kit",
        ],
      },
      {
        name: "Premium",
        price: "$1,200",
        inclusions: [
          "Bridal hair + makeup",
          "Up to 4 bridesmaids",
          "Full trial session",
          "Airbrush foundation",
          "Lashes included",
          "On-location (DFW area)",
          "Touch-up artist for ceremony",
        ],
      },
    ],
  },
  {
    id: "ivory-films",
    name: "Ivory Films",
    category: "Videography",
    location: "Houston, TX",
    priceRange: "$$$",
    rating: 5.0,
    reviews: 54,
    tag: "Featured",
    description:
      "Cinematic wedding films that feel like short movies. Ivory Films brings a feature-film sensibility to every wedding, delivering footage you'll watch for decades.",
    bio: [
      "Ivory Films was founded by husband-and-wife duo James and Chloe Park, who met on a film set and have been telling love stories ever since. Their approach to wedding videography is rooted in cinematic storytelling — every film they create has a narrative arc, intentional pacing, and a score that elevates the emotion.",
      "James handles the main camera and drone work, while Chloe captures the behind-the-scenes moments: the quiet glances, the tears, the laughter that happens when no one's watching. Together they create a complete picture of your wedding day that no single camera could capture alone.",
      "Ivory Films delivers a full-length documentary cut alongside a cinematic highlight film, giving couples both a keepsake record and a film they can share with friends and family. Turnaround is 8–12 weeks, with rush delivery available for an additional fee.",
    ],
    yearsExperience: 6,
    weddingsDone: 130,
    responseTime: "Within 24 hours",
    services: [
      "Cinematic highlight film (3–5 min)",
      "Full ceremony & reception film",
      "Drone aerial footage",
      "Engagement film session",
      "Same-day edit (ceremony only)",
      "Raw footage delivery",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$2,800",
        inclusions: [
          "6 hours of coverage",
          "1 videographer",
          "3-minute highlight film",
          "Online delivery",
          "10-week turnaround",
        ],
      },
      {
        name: "Standard",
        price: "$4,500",
        inclusions: [
          "8 hours of coverage",
          "2 videographers",
          "5-minute highlight film",
          "Full ceremony film",
          "Drone footage",
          "Online + USB delivery",
          "8-week turnaround",
        ],
      },
      {
        name: "Premium",
        price: "$6,800",
        inclusions: [
          "10 hours of coverage",
          "2 videographers",
          "5-minute highlight + full film",
          "Drone footage",
          "Engagement film session",
          "Same-day ceremony edit",
          "Online + USB + USB backup",
          "6-week turnaround",
        ],
      },
    ],
  },
  {
    id: "planner-co",
    name: "The Planner Co.",
    category: "Planning",
    location: "San Antonio, TX",
    priceRange: "$$–$$$$",
    rating: 4.7,
    reviews: 203,
    tag: "Top Rated",
    description:
      "Expert wedding planning from first vision to final send-off. The Planner Co. takes the stress out of planning so you can enjoy every moment of your engagement.",
    bio: [
      "The Planner Co. is a full-service wedding planning studio led by founder and lead planner Rachel Nguyen. With over 12 years of experience across hundreds of Texas weddings, Rachel and her team are known for their meticulous attention to detail, calm under pressure, and ability to bring any vision to life.",
      "The studio offers three levels of service — full planning, partial planning, and day-of coordination — so couples can choose the level of support that fits their needs and budget. Each package begins with a deep-dive discovery session to understand your aesthetic, priorities, and non-negotiables.",
      "The Planner Co. has relationships with the best vendors across Texas, which means better deals, smoother logistics, and a day that runs exactly as planned. Past clients consistently describe Rachel as the best investment they made in their entire wedding budget.",
    ],
    yearsExperience: 12,
    weddingsDone: 480,
    responseTime: "Within 4 hours",
    services: [
      "Full wedding planning & design",
      "Partial planning (6-month support)",
      "Day-of coordination",
      "Vendor sourcing & negotiation",
      "Budget management",
      "Rehearsal dinner coordination",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$2,500",
        inclusions: [
          "Day-of coordination",
          "Vendor confirmation calls",
          "Timeline creation",
          "Ceremony rehearsal",
          "10 hours on wedding day",
          "1 coordinator",
        ],
      },
      {
        name: "Standard",
        price: "$5,500",
        inclusions: [
          "6-month partial planning",
          "Vendor recommendations",
          "Budget tracking",
          "2 in-person meetings",
          "Full day-of coordination",
          "2 coordinators on wedding day",
        ],
      },
      {
        name: "Premium",
        price: "$9,500",
        inclusions: [
          "Full planning (12+ months)",
          "Complete vendor sourcing",
          "Design & décor planning",
          "Budget management",
          "Unlimited meetings & calls",
          "Rehearsal dinner included",
          "2 coordinators on wedding day",
          "Post-wedding wrap-up",
        ],
      },
    ],
  },
  {
    id: "grand-estate",
    name: "The Grand Estate",
    category: "Venues",
    location: "Austin, TX",
    priceRange: "$$$$",
    rating: 4.9,
    reviews: 78,
    tag: "Top Rated",
    description:
      "A sprawling Hill Country estate with breathtaking views and elegant indoor-outdoor spaces. The Grand Estate sets the stage for weddings of 50 to 500 guests.",
    bio: [
      "Nestled in the rolling hills just outside Austin, The Grand Estate is one of Texas's most sought-after wedding venues. Set on 40 acres of manicured grounds, the property features a grand manor house, outdoor ceremony lawns, a covered pavilion, and a picturesque lake — all available exclusively for your event.",
      "The venue team works hand-in-hand with each couple to ensure every detail of the space is configured perfectly. From table arrangements and lighting rigs to parking logistics and vendor access, the in-house events team handles it all, making The Grand Estate a genuinely stress-free choice.",
      "The Estate is vendor-flexible, allowing couples to bring their preferred caterers, photographers, and planners while also offering an approved vendor list for those who prefer a fully guided experience. Weekday and off-season discounts are available for budget-conscious couples who want the luxury without the full price tag.",
    ],
    yearsExperience: 15,
    weddingsDone: 320,
    responseTime: "Within 48 hours",
    services: [
      "Indoor ballroom (capacity 300)",
      "Outdoor ceremony lawn",
      "Covered pavilion (capacity 500)",
      "Bridal suite & groom's quarters",
      "Parking for 200+ vehicles",
      "Overnight accommodation (10 rooms)",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$6,500",
        inclusions: [
          "6-hour venue hire (weekday)",
          "Ceremony lawn",
          "Bridal suite access",
          "Basic lighting package",
          "Tables & chairs (100 guests)",
          "On-site coordinator",
        ],
      },
      {
        name: "Standard",
        price: "$11,000",
        inclusions: [
          "10-hour venue hire",
          "Ceremony lawn + pavilion",
          "Bridal + groom suite",
          "Premium lighting package",
          "Tables, chairs & linens (200 guests)",
          "On-site coordinator",
          "Parking & valet",
        ],
      },
      {
        name: "Premium",
        price: "$18,500",
        inclusions: [
          "Full weekend exclusive hire",
          "All indoor + outdoor spaces",
          "Bridal + groom suite",
          "Custom lighting & draping",
          "Full furniture package (500 guests)",
          "Dedicated events team",
          "10 overnight rooms",
          "Rehearsal dinner included",
        ],
      },
    ],
  },
  {
    id: "paper-petal",
    name: "Paper & Petal Studio",
    category: "Invitations",
    location: "Dallas, TX",
    priceRange: "$–$$",
    rating: 4.8,
    reviews: 93,
    tag: "Popular",
    description:
      "Handcrafted wedding stationery and invitation suites that set the tone for your entire celebration. Paper & Petal creates heirloom pieces couples treasure forever.",
    bio: [
      "Paper & Petal Studio was founded by stationery designer and letterpress artist Clara Osei, who turned her love of paper crafts into a thriving wedding stationery business. Based in Dallas, Clara designs invitation suites, day-of stationery, and keepsake pieces that are as beautiful in person as they are in photos.",
      "Every suite is a complete design system — from the save-the-date through to the menu cards and favour tags. Clara works through a detailed design brief with each couple, ensuring the stationery reflects the wedding's aesthetic, colour palette, and overall tone. Semi-custom templates and fully bespoke designs are both available.",
      "Paper & Petal prints on premium cotton and textured papers using a combination of digital, letterpress, and foil stamping techniques. Clara is particularly known for her hand-painted watercolour details and botanical borders, which can be adapted to almost any colour scheme.",
    ],
    yearsExperience: 6,
    weddingsDone: 240,
    responseTime: "Within 24 hours",
    services: [
      "Full invitation suite design",
      "Save-the-dates",
      "Day-of stationery (menus, programmes)",
      "Place cards & escort cards",
      "Thank-you card design",
      "Custom envelope addressing",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$380",
        inclusions: [
          "Semi-custom invitation (50 sets)",
          "Digital proofing",
          "Standard card stock",
          "Addressed envelopes",
          "Free shipping",
        ],
      },
      {
        name: "Standard",
        price: "$780",
        inclusions: [
          "Custom invitation suite (100 sets)",
          "Save-the-date cards",
          "Digital + physical proofing",
          "Premium card stock",
          "Envelope liner",
          "Free shipping",
        ],
      },
      {
        name: "Premium",
        price: "$1,600",
        inclusions: [
          "Fully bespoke suite (150 sets)",
          "Save-the-dates + day-of stationery",
          "Letterpress or foil accent option",
          "Hand-painted watercolour element",
          "Wax seal set",
          "Premium vellum overlay",
          "White glove packaging",
        ],
      },
    ],
  },
  {
    id: "sweet-tokens",
    name: "Sweet Tokens",
    category: "Favours",
    location: "Houston, TX",
    priceRange: "$",
    rating: 4.6,
    reviews: 47,
    tag: "New",
    description:
      "Beautifully packaged wedding favours made with love. Sweet Tokens creates personalised keepsakes that guests genuinely want to take home.",
    bio: [
      "Sweet Tokens is a Houston-based wedding favour company founded by sisters Amara and Jade Williams. What started as a hobby — hand-packaging chocolate truffles for friends' weddings — has grown into a thriving business that ships personalised favours to couples across Texas and nationwide.",
      "Amara and Jade believe favours should be something guests actually want, not something destined for the bin. Their range includes artisan honey jars, handmade candles, personalised spice blends, luxury bath bombs, and gourmet chocolate truffles — all packaged in beautifully designed boxes and bags with custom tags.",
      "Every favour is made to order, meaning couples can choose their products, scents, flavours, and packaging colours to match their wedding palette. Bulk discounts are available from 50 units, and rush orders can be accommodated with advance notice.",
    ],
    yearsExperience: 3,
    weddingsDone: 85,
    responseTime: "Within 24 hours",
    services: [
      "Artisan honey jars (custom labels)",
      "Handmade soy candles",
      "Gourmet chocolate truffles",
      "Personalised spice blend sets",
      "Luxury bath bomb sets",
      "Custom packaging & tags",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "From $4/unit",
        inclusions: [
          "50+ units minimum",
          "Choice of 1 favour product",
          "Custom tag (name + date)",
          "Standard gift bag packaging",
          "Bulk shipping included",
        ],
      },
      {
        name: "Standard",
        price: "From $7/unit",
        inclusions: [
          "50+ units minimum",
          "Choice of 2 favour products",
          "Custom tag + ribbon",
          "Premium gift box packaging",
          "Personalised message card",
          "Bulk shipping included",
        ],
      },
      {
        name: "Premium",
        price: "From $12/unit",
        inclusions: [
          "50+ units minimum",
          "Choice of 3 favour products",
          "Custom box with foil name",
          "Wax seal sticker",
          "Personalised message card",
          "Tissue paper + ribbon",
          "Priority production & shipping",
        ],
      },
    ],
  },
  {
    id: "wanderlust-escapes",
    name: "Wanderlust Escapes",
    category: "Honeymoon",
    location: "Austin, TX",
    priceRange: "$$$–$$$$",
    rating: 4.9,
    reviews: 38,
    tag: "New",
    description:
      "Bespoke honeymoon planning for couples who want something extraordinary. Wanderlust Escapes designs once-in-a-lifetime trips tailored to your dreams.",
    bio: [
      "Wanderlust Escapes is a luxury honeymoon planning boutique founded by travel designer Priya Mehta, who has personally visited over 60 countries and knows what makes a trip truly extraordinary. Based in Austin, Priya works with newlyweds to design honeymoons that go far beyond a standard package tour.",
      "Every itinerary is built from scratch. Priya starts with a deep discovery session to understand the couple's travel style, bucket-list destinations, preferred pace, and budget. From there she crafts a day-by-day journey complete with hand-picked hotels, private experiences, restaurant reservations, and airport transfers — all pre-arranged so couples can focus entirely on each other.",
      "Wanderlust Escapes has preferred partner relationships with luxury hotel groups across the Maldives, Italy, Japan, and the Caribbean, meaning clients regularly receive suite upgrades, complimentary breakfasts, and special touches that money alone can't buy. Priya remains on call throughout the trip in case anything needs adjusting.",
    ],
    yearsExperience: 8,
    weddingsDone: 92,
    responseTime: "Within 12 hours",
    services: [
      "Full honeymoon itinerary design",
      "Flight booking & upgrades",
      "Luxury hotel sourcing",
      "Private tours & experiences",
      "Restaurant reservations",
      "Travel insurance guidance",
    ],
    pricingTiers: [
      {
        name: "Basic",
        price: "$500 planning fee",
        inclusions: [
          "Destination consultation",
          "7-day itinerary outline",
          "Hotel recommendations (3 options)",
          "Flight search support",
          "Digital travel document folder",
        ],
      },
      {
        name: "Standard",
        price: "$1,200 planning fee",
        inclusions: [
          "Full 10-day itinerary",
          "Hotel bookings (all managed)",
          "Flight booking included",
          "2 private experience bookings",
          "Restaurant reservations",
          "24/7 on-trip support",
        ],
      },
      {
        name: "Premium",
        price: "$2,500 planning fee",
        inclusions: [
          "Fully bespoke 14-day journey",
          "All bookings managed",
          "Business class flight search",
          "Luxury hotel suite upgrades",
          "Private transfers throughout",
          "5+ exclusive experiences",
          "Personal travel concierge",
          "24/7 on-trip support",
        ],
      },
    ],
  },
];
